# Title of your blog; shows in the header
name: "KDL Tech Blog"

# Description of your content (will only be used on Google Search)
description: "Web Developer Company from Somewhere"

# Your name. Will show in your footer + sidebar
author: "KDL"
lang: ja
timezone: Asia/Tokyo

url: "https://kobedigitallabo.github.io"
baseurl: ""

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: ""

# Social Accounts (mine, as placeholders)
twitter:
github: kobedigitallabo
dribbble:
instagram:
googleplus:

# Google Analytics (you may want to changes these with yours or even delete :)
ga_tracking_id: UA-83000444-1

# Handling Reading
exclude: ["README.md", ".gitignore", "Gemfile", "Gemfile.lock", "vendor", "art"]

# Plugins
gems: [jekyll-redirect-from, jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Conversion
markdown: kramdown
highlighter: rouge

# Outputting
permalink: pretty
paginate: 5
paginate_path: "/page/:num"

# Markdown Processors
kramdown:
  input: GFM

# SCSS
sass:
  sass_dir: _scss
  style: :compressed

